FROM node:16.13.1

WORKDIR /app 

COPY package.json /app 
COPY yarn.lock /app

RUN yarn install --immutable --immutable-cache --check-cache

COPY . /app 

RUN yarn build critterz

CMD ["node","dist/apps/critterz/main"]