export const toFarmDto = {
  contractAddress: 'contract.address',
  contractAbi: 'contract.abi',
  contractName: 'contract.name',
  contractSource: 'contract.source',
  currencyAddress: 'currency.address',
  currencyName: 'currency.name',
  currencyDecimals: 'currency.decimals',
  dailyRoi: 'dailyRoi',
  fee: 'fee',
  psn: 'psn',
  psnh: 'psnh',
  name: 'name',
  referralBonus: 'referralBonus',
  seedBlock: 'seedBlock',
  seedTimestamp: 'seedTimestamp',
  websiteUrl: 'websiteUrl',
};
